apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  creationTimestamp: "2023-10-24T12:01:11Z"
  generateName: auto-certs-
  generation: 56
  labels:
    workflows.argoproj.io/creator: system-serviceaccount-argocd-argo-workflows-server
  name: auto-certsqqwrf
  namespace: workflows
  resourceVersion: "872497"
  uid: d9748331-6a13-4ffa-835b-5f5b8134de39
spec:
  arguments:
    parameters:
    - name: expire
      value: "604800"
    - name: acme-environment
      value: ""
    - name: acme-configmap
      value: acme
    - name: acme-key
      value: acme.sh
  entrypoint: update-expire-secret
  templates:
  - inputs:
      parameters:
      - name: expire
      - name: acme-environment
      - name: acme-configmap
      - name: acme-key
    metadata: {}
    name: update-expire-secret
    outputs: {}
    steps:
    - - arguments: {}
        name: list-secret
        template: list-secret
    - - arguments:
          parameters:
          - name: name
            value: '{{item.name}}'
          - name: namespace
            value: '{{item.namespace}}'
          - name: certificate
            value: '{{item.certificate}}'
          - name: acme-environment
            value: '{{inputs.parameters.acme-environment}}'
          - name: acme-configmap
            value: '{{inputs.parameters.acme-configmap}}'
          - name: acme-key
            value: '{{inputs.parameters.acme-key}}'
          - name: expire
            value: '{{inputs.parameters.expire}}'
        name: check-and-update
        template: check-and-update
        withParam: '{{steps.list-secret.outputs.result}}'
    - - arguments:
          parameters:
          - name: result
            value: '{{steps.check-and-update.outputs.parameters.result }}'
        name: display
        template: display
  - inputs: {}
    metadata: {}
    name: list-secret
    outputs: {}
    script:
      command:
      - bash
      image: bitnami/kubectl:latest
      name: ""
      resources: {}
      source: |
        kubectl get secret -A --field-selector type=kubernetes.io/tls -o jsonpath='{range .items[*]}{"{\"certificate\":\""}{.data.tls\.crt}{"\",\"name\":\""}{.metadata.name}{"\",\"namespace\":\""}{.metadata.namespace}{"\"},"}{end}'| awk '{if (NR>1) {print s;} s=$0} END {sub(",$", "", s); print s}'|  awk 'BEGIN {print "["} {print $0} END {print "]"}'
  - inputs:
      parameters:
      - name: namespace
      - name: name
      - name: certificate
      - name: acme-environment
      - name: acme-configmap
      - name: acme-key
      - name: expire
    metadata: {}
    name: check-and-update
    outputs:
      parameters:
      - name: result
        valueFrom:
          parameter: '{{steps.update-cert.outputs.result}}'
    steps:
    - - arguments:
          parameters:
          - name: certificate
            value: '{{inputs.parameters.certificate}}'
          - name: expire
            value: '{{inputs.parameters.expire}}'
        name: check-expire
        template: check-expire
    - - arguments:
          parameters:
          - name: certificate
            value: '{{inputs.parameters.certificate}}'
          - name: environment
            value: '{{inputs.parameters.acme-environment}}'
          - name: acme
            valueFrom:
              configMapKeyRef:
                key: '{{inputs.parameters.acme-key}}'
                name: '{{inputs.parameters.acme-configmap}}'
        name: update-cert
        template: update-cert
        when: '{{steps.check-expire.outputs.result}} == true'
  - inputs:
      parameters:
      - name: certificate
      - name: expire
    metadata: {}
    name: check-expire
    outputs: {}
    script:
      command:
      - bash
      image: bitnami/kubectl:latest
      name: ""
      resources: {}
      source: echo "{{inputs.parameters.certificate}}"|base64 --decode | openssl x509
        -noout -enddate |  cut -d "=" -f 2- | xargs -I{} sh -c 'if [ $(date -d "{}"
        +%s) -lt $(($(date +%s) + {{inputs.parameters.expire}})) ]; then echo "true";else
        echo "false";fi'
  - inputs:
      parameters:
      - name: environment
      - name: certificate
      - name: acme
    metadata: {}
    name: update-cert
    outputs: {}
    script:
      command:
      - bash
      image: bitnami/kubectl:latest
      name: ""
      resources: {}
      # TODO: use acme.sh update certificate.
      source: echo "{{inputs.parameters.certificate}}"| base64 --decode | openssl
        x509 -text -noout | grep "Subject:" | awk -F 'CN =' '{print $2}' | xargs -I{}
        sh -c 'echo [{\"domain\":\"{}\"}]'
  - inputs:
      parameters:
      - name: result
    metadata: {}
    name: display
    outputs: {}
    script:
      command:
      - bash
      image: bitnami/kubectl:latest
      name: ""
      resources: {}
      # TODO: use email to notify result
      source: echo "{{ inputs.parameters.result }}"