apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: auto-certs-
  name: auto-certsq
spec:
  arguments:
    parameters:
    - name: expire
      value: "604800"
  entrypoint: list-expire-secret
  templates:
  - inputs: {}
    metadata: {}
    name: list-expire-secret
    outputs: {}
    steps:
    - - arguments: {}
        name: list-secret
        template: list-secret
    - - arguments:
          parameters:
          - name: name
            value: '{{item.name}}'
          - name: certificate
            value: '{{item.certificate}}'
          - name: namespace
            value: '{{item.namespace}}'
          - name: expire
            value: '{{workflow.parameters.expire}}'
        name: check-expire
        template: check-expire
        withParam: '{{steps.list-secret.outputs.result}}'
  - inputs: {}
    metadata: {}
    name: list-secret
    outputs: {}
    script:
      command:
      - bash
      image: bitnami/kubectl:latest
      name: ""
      resources: {}
      source: |
        kubectl get secret -A --field-selector type=kubernetes.io/tls -o jsonpath='{range .items[*]}{"{\"certificate\":\""}{.data.tls\.crt}{"\",\"name\":\""}{.metadata.name}{"\",\"namespace\":\""}{.metadata.namespace}{"\"},"}{end}'| awk '{if (NR>1) {print s;} s=$0} END {sub(",$", "", s); print s}'|  awk 'BEGIN {print "["} {print $0} END {print "]"}'
  - inputs:
      parameters:
      - name: name
      - name: certificate
      - name: namespace
      - name: expire
    metadata: {}
    name: check-expire
    outputs: {}
    script:
      command:
      - bash
      image: bitnami/kubectl:latest
      name: ""
      resources: {}
      source: |
        echo "{{inputs.parameters.certificate}}" | base64 --decode |  openssl x509 -noout -enddate | cut -d "=" -f 2- | xargs -I{} sh -c 'if [ $(date -d "{}" +%s) -lt $(($(date +%s) + {{inputs.parameters.expire}})) ]; then echo "😁"; else echo "😟"; fi'
